package com.mechinn.android.ouralliance.greenDao.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.mechinn.android.ouralliance.greenDao.dao.TeamDao;
import com.mechinn.android.ouralliance.greenDao.dao.MultimediaDao;
import com.mechinn.android.ouralliance.greenDao.dao.Event2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.EventTeam2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.Match2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.TeamScouting2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.Wheel2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.MatchScouting2014Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        TeamDao.createTable(db, ifNotExists);
        MultimediaDao.createTable(db, ifNotExists);
        Event2014Dao.createTable(db, ifNotExists);
        EventTeam2014Dao.createTable(db, ifNotExists);
        Match2014Dao.createTable(db, ifNotExists);
        TeamScouting2014Dao.createTable(db, ifNotExists);
        Wheel2014Dao.createTable(db, ifNotExists);
        MatchScouting2014Dao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        TeamDao.dropTable(db, ifExists);
        MultimediaDao.dropTable(db, ifExists);
        Event2014Dao.dropTable(db, ifExists);
        EventTeam2014Dao.dropTable(db, ifExists);
        Match2014Dao.dropTable(db, ifExists);
        TeamScouting2014Dao.dropTable(db, ifExists);
        Wheel2014Dao.dropTable(db, ifExists);
        MatchScouting2014Dao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(TeamDao.class);
        registerDaoClass(MultimediaDao.class);
        registerDaoClass(Event2014Dao.class);
        registerDaoClass(EventTeam2014Dao.class);
        registerDaoClass(Match2014Dao.class);
        registerDaoClass(TeamScouting2014Dao.class);
        registerDaoClass(Wheel2014Dao.class);
        registerDaoClass(MatchScouting2014Dao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
