package com.mechinn.android.ouralliance.greenDao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mechinn.android.ouralliance.greenDao.Team;
import com.mechinn.android.ouralliance.greenDao.Multimedia;
import com.mechinn.android.ouralliance.greenDao.Event2014;
import com.mechinn.android.ouralliance.greenDao.EventTeam2014;
import com.mechinn.android.ouralliance.greenDao.Match2014;
import com.mechinn.android.ouralliance.greenDao.TeamScouting2014;
import com.mechinn.android.ouralliance.greenDao.Wheel2014;
import com.mechinn.android.ouralliance.greenDao.MatchScouting2014;

import com.mechinn.android.ouralliance.greenDao.dao.TeamDao;
import com.mechinn.android.ouralliance.greenDao.dao.MultimediaDao;
import com.mechinn.android.ouralliance.greenDao.dao.Event2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.EventTeam2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.Match2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.TeamScouting2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.Wheel2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.MatchScouting2014Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teamDaoConfig;
    private final DaoConfig multimediaDaoConfig;
    private final DaoConfig event2014DaoConfig;
    private final DaoConfig eventTeam2014DaoConfig;
    private final DaoConfig match2014DaoConfig;
    private final DaoConfig teamScouting2014DaoConfig;
    private final DaoConfig wheel2014DaoConfig;
    private final DaoConfig matchScouting2014DaoConfig;

    private final TeamDao teamDao;
    private final MultimediaDao multimediaDao;
    private final Event2014Dao event2014Dao;
    private final EventTeam2014Dao eventTeam2014Dao;
    private final Match2014Dao match2014Dao;
    private final TeamScouting2014Dao teamScouting2014Dao;
    private final Wheel2014Dao wheel2014Dao;
    private final MatchScouting2014Dao matchScouting2014Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teamDaoConfig = daoConfigMap.get(TeamDao.class).clone();
        teamDaoConfig.initIdentityScope(type);

        multimediaDaoConfig = daoConfigMap.get(MultimediaDao.class).clone();
        multimediaDaoConfig.initIdentityScope(type);

        event2014DaoConfig = daoConfigMap.get(Event2014Dao.class).clone();
        event2014DaoConfig.initIdentityScope(type);

        eventTeam2014DaoConfig = daoConfigMap.get(EventTeam2014Dao.class).clone();
        eventTeam2014DaoConfig.initIdentityScope(type);

        match2014DaoConfig = daoConfigMap.get(Match2014Dao.class).clone();
        match2014DaoConfig.initIdentityScope(type);

        teamScouting2014DaoConfig = daoConfigMap.get(TeamScouting2014Dao.class).clone();
        teamScouting2014DaoConfig.initIdentityScope(type);

        wheel2014DaoConfig = daoConfigMap.get(Wheel2014Dao.class).clone();
        wheel2014DaoConfig.initIdentityScope(type);

        matchScouting2014DaoConfig = daoConfigMap.get(MatchScouting2014Dao.class).clone();
        matchScouting2014DaoConfig.initIdentityScope(type);

        teamDao = new TeamDao(teamDaoConfig, this);
        multimediaDao = new MultimediaDao(multimediaDaoConfig, this);
        event2014Dao = new Event2014Dao(event2014DaoConfig, this);
        eventTeam2014Dao = new EventTeam2014Dao(eventTeam2014DaoConfig, this);
        match2014Dao = new Match2014Dao(match2014DaoConfig, this);
        teamScouting2014Dao = new TeamScouting2014Dao(teamScouting2014DaoConfig, this);
        wheel2014Dao = new Wheel2014Dao(wheel2014DaoConfig, this);
        matchScouting2014Dao = new MatchScouting2014Dao(matchScouting2014DaoConfig, this);

        registerDao(Team.class, teamDao);
        registerDao(Multimedia.class, multimediaDao);
        registerDao(Event2014.class, event2014Dao);
        registerDao(EventTeam2014.class, eventTeam2014Dao);
        registerDao(Match2014.class, match2014Dao);
        registerDao(TeamScouting2014.class, teamScouting2014Dao);
        registerDao(Wheel2014.class, wheel2014Dao);
        registerDao(MatchScouting2014.class, matchScouting2014Dao);
    }
    
    public void clear() {
        teamDaoConfig.getIdentityScope().clear();
        multimediaDaoConfig.getIdentityScope().clear();
        event2014DaoConfig.getIdentityScope().clear();
        eventTeam2014DaoConfig.getIdentityScope().clear();
        match2014DaoConfig.getIdentityScope().clear();
        teamScouting2014DaoConfig.getIdentityScope().clear();
        wheel2014DaoConfig.getIdentityScope().clear();
        matchScouting2014DaoConfig.getIdentityScope().clear();
    }

    public TeamDao getTeamDao() {
        return teamDao;
    }

    public MultimediaDao getMultimediaDao() {
        return multimediaDao;
    }

    public Event2014Dao getEvent2014Dao() {
        return event2014Dao;
    }

    public EventTeam2014Dao getEventTeam2014Dao() {
        return eventTeam2014Dao;
    }

    public Match2014Dao getMatch2014Dao() {
        return match2014Dao;
    }

    public TeamScouting2014Dao getTeamScouting2014Dao() {
        return teamScouting2014Dao;
    }

    public Wheel2014Dao getWheel2014Dao() {
        return wheel2014Dao;
    }

    public MatchScouting2014Dao getMatchScouting2014Dao() {
        return matchScouting2014Dao;
    }

}
