package com.mechinn.android.ouralliance.greenDao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mechinn.android.ouralliance.greenDao.Team;
import com.mechinn.android.ouralliance.greenDao.Multimedia;
import com.mechinn.android.ouralliance.greenDao.Event;
import com.mechinn.android.ouralliance.greenDao.EventTeam;
import com.mechinn.android.ouralliance.greenDao.Match;
import com.mechinn.android.ouralliance.greenDao.Wheel;
import com.mechinn.android.ouralliance.greenDao.TeamScouting2014;
import com.mechinn.android.ouralliance.greenDao.MatchScouting2014;

import com.mechinn.android.ouralliance.greenDao.dao.TeamDao;
import com.mechinn.android.ouralliance.greenDao.dao.MultimediaDao;
import com.mechinn.android.ouralliance.greenDao.dao.EventDao;
import com.mechinn.android.ouralliance.greenDao.dao.EventTeamDao;
import com.mechinn.android.ouralliance.greenDao.dao.MatchDao;
import com.mechinn.android.ouralliance.greenDao.dao.WheelDao;
import com.mechinn.android.ouralliance.greenDao.dao.TeamScouting2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.MatchScouting2014Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teamDaoConfig;
    private final DaoConfig multimediaDaoConfig;
    private final DaoConfig eventDaoConfig;
    private final DaoConfig eventTeamDaoConfig;
    private final DaoConfig matchDaoConfig;
    private final DaoConfig wheelDaoConfig;
    private final DaoConfig teamScouting2014DaoConfig;
    private final DaoConfig matchScouting2014DaoConfig;

    private final TeamDao teamDao;
    private final MultimediaDao multimediaDao;
    private final EventDao eventDao;
    private final EventTeamDao eventTeamDao;
    private final MatchDao matchDao;
    private final WheelDao wheelDao;
    private final TeamScouting2014Dao teamScouting2014Dao;
    private final MatchScouting2014Dao matchScouting2014Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teamDaoConfig = daoConfigMap.get(TeamDao.class).clone();
        teamDaoConfig.initIdentityScope(type);

        multimediaDaoConfig = daoConfigMap.get(MultimediaDao.class).clone();
        multimediaDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        eventTeamDaoConfig = daoConfigMap.get(EventTeamDao.class).clone();
        eventTeamDaoConfig.initIdentityScope(type);

        matchDaoConfig = daoConfigMap.get(MatchDao.class).clone();
        matchDaoConfig.initIdentityScope(type);

        wheelDaoConfig = daoConfigMap.get(WheelDao.class).clone();
        wheelDaoConfig.initIdentityScope(type);

        teamScouting2014DaoConfig = daoConfigMap.get(TeamScouting2014Dao.class).clone();
        teamScouting2014DaoConfig.initIdentityScope(type);

        matchScouting2014DaoConfig = daoConfigMap.get(MatchScouting2014Dao.class).clone();
        matchScouting2014DaoConfig.initIdentityScope(type);

        teamDao = new TeamDao(teamDaoConfig, this);
        multimediaDao = new MultimediaDao(multimediaDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);
        eventTeamDao = new EventTeamDao(eventTeamDaoConfig, this);
        matchDao = new MatchDao(matchDaoConfig, this);
        wheelDao = new WheelDao(wheelDaoConfig, this);
        teamScouting2014Dao = new TeamScouting2014Dao(teamScouting2014DaoConfig, this);
        matchScouting2014Dao = new MatchScouting2014Dao(matchScouting2014DaoConfig, this);

        registerDao(Team.class, teamDao);
        registerDao(Multimedia.class, multimediaDao);
        registerDao(Event.class, eventDao);
        registerDao(EventTeam.class, eventTeamDao);
        registerDao(Match.class, matchDao);
        registerDao(Wheel.class, wheelDao);
        registerDao(TeamScouting2014.class, teamScouting2014Dao);
        registerDao(MatchScouting2014.class, matchScouting2014Dao);
    }
    
    public void clear() {
        teamDaoConfig.getIdentityScope().clear();
        multimediaDaoConfig.getIdentityScope().clear();
        eventDaoConfig.getIdentityScope().clear();
        eventTeamDaoConfig.getIdentityScope().clear();
        matchDaoConfig.getIdentityScope().clear();
        wheelDaoConfig.getIdentityScope().clear();
        teamScouting2014DaoConfig.getIdentityScope().clear();
        matchScouting2014DaoConfig.getIdentityScope().clear();
    }

    public TeamDao getTeamDao() {
        return teamDao;
    }

    public MultimediaDao getMultimediaDao() {
        return multimediaDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public EventTeamDao getEventTeamDao() {
        return eventTeamDao;
    }

    public MatchDao getMatchDao() {
        return matchDao;
    }

    public WheelDao getWheelDao() {
        return wheelDao;
    }

    public TeamScouting2014Dao getTeamScouting2014Dao() {
        return teamScouting2014Dao;
    }

    public MatchScouting2014Dao getMatchScouting2014Dao() {
        return matchScouting2014Dao;
    }

}
