package com.mechinn.android.ouralliance.greenDao.frc2014.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.mechinn.android.ouralliance.greenDao.frc2014.Competition;
import com.mechinn.android.ouralliance.greenDao.frc2014.Team;

import com.mechinn.android.ouralliance.greenDao.frc2014.CompetitionTeam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table COMPETITION_TEAM.
*/
public class CompetitionTeamDao extends AbstractDao<CompetitionTeam, Long> {

    public static final String TABLENAME = "COMPETITION_TEAM";

    /**
     * Properties of entity CompetitionTeam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Modified = new Property(1, java.util.Date.class, "modified", false, "MODIFIED");
        public final static Property Competition = new Property(2, Long.class, "competition", false, "COMPETITION");
        public final static Property Team = new Property(3, Long.class, "team", false, "TEAM");
        public final static Property Rank = new Property(4, Integer.class, "rank", false, "RANK");
        public final static Property Scouted = new Property(5, Boolean.class, "scouted", false, "SCOUTED");
    };

    private DaoSession daoSession;


    public CompetitionTeamDao(DaoConfig config) {
        super(config);
    }
    
    public CompetitionTeamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COMPETITION_TEAM' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MODIFIED' INTEGER," + // 1: modified
                "'COMPETITION' INTEGER," + // 2: competition
                "'TEAM' INTEGER," + // 3: team
                "'RANK' INTEGER," + // 4: rank
                "'SCOUTED' INTEGER);"); // 5: scouted
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COMPETITION_TEAM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CompetitionTeam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date modified = entity.getModified();
        if (modified != null) {
            stmt.bindLong(2, modified.getTime());
        }
 
        Long competition = entity.getCompetition();
        if (competition != null) {
            stmt.bindLong(3, competition);
        }
 
        Long team = entity.getTeam();
        if (team != null) {
            stmt.bindLong(4, team);
        }
 
        Integer rank = entity.getRank();
        if (rank != null) {
            stmt.bindLong(5, rank);
        }
 
        Boolean scouted = entity.getScouted();
        if (scouted != null) {
            stmt.bindLong(6, scouted ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(CompetitionTeam entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CompetitionTeam readEntity(Cursor cursor, int offset) {
        CompetitionTeam entity = new CompetitionTeam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // modified
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // competition
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // team
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // rank
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // scouted
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CompetitionTeam entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setModified(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setCompetition(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTeam(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setRank(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setScouted(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CompetitionTeam entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CompetitionTeam entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCompetitionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTeamDao().getAllColumns());
            builder.append(" FROM COMPETITION_TEAM T");
            builder.append(" LEFT JOIN COMPETITION T0 ON T.'COMPETITION'=T0.'_id'");
            builder.append(" LEFT JOIN TEAM T1 ON T.'TEAM'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CompetitionTeam loadCurrentDeep(Cursor cursor, boolean lock) {
        CompetitionTeam entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Competition competition = loadCurrentOther(daoSession.getCompetitionDao(), cursor, offset);
        entity.setCompetition(competition);
        offset += daoSession.getCompetitionDao().getAllColumns().length;

        Team team = loadCurrentOther(daoSession.getTeamDao(), cursor, offset);
        entity.setTeam(team);

        return entity;    
    }

    public CompetitionTeam loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CompetitionTeam> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CompetitionTeam> list = new ArrayList<CompetitionTeam>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CompetitionTeam> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CompetitionTeam> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
