package com.mechinn.android.ouralliance.greenDao.frc2014.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.mechinn.android.ouralliance.greenDao.frc2014.dao.TeamDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.CompetitionDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.CompetitionTeamDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.MatchDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.TeamScoutingDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.WheelDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.MatchScoutingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        TeamDao.createTable(db, ifNotExists);
        CompetitionDao.createTable(db, ifNotExists);
        CompetitionTeamDao.createTable(db, ifNotExists);
        MatchDao.createTable(db, ifNotExists);
        TeamScoutingDao.createTable(db, ifNotExists);
        WheelDao.createTable(db, ifNotExists);
        MatchScoutingDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        TeamDao.dropTable(db, ifExists);
        CompetitionDao.dropTable(db, ifExists);
        CompetitionTeamDao.dropTable(db, ifExists);
        MatchDao.dropTable(db, ifExists);
        TeamScoutingDao.dropTable(db, ifExists);
        WheelDao.dropTable(db, ifExists);
        MatchScoutingDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(TeamDao.class);
        registerDaoClass(CompetitionDao.class);
        registerDaoClass(CompetitionTeamDao.class);
        registerDaoClass(MatchDao.class);
        registerDaoClass(TeamScoutingDao.class);
        registerDaoClass(WheelDao.class);
        registerDaoClass(MatchScoutingDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
