package com.mechinn.android.ouralliance.greenDao.frc2014.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mechinn.android.ouralliance.greenDao.frc2014.Team;
import com.mechinn.android.ouralliance.greenDao.frc2014.Competition;
import com.mechinn.android.ouralliance.greenDao.frc2014.CompetitionTeam;
import com.mechinn.android.ouralliance.greenDao.frc2014.Match;
import com.mechinn.android.ouralliance.greenDao.frc2014.TeamScouting;
import com.mechinn.android.ouralliance.greenDao.frc2014.Wheel;
import com.mechinn.android.ouralliance.greenDao.frc2014.MatchScouting;

import com.mechinn.android.ouralliance.greenDao.frc2014.dao.TeamDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.CompetitionDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.CompetitionTeamDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.MatchDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.TeamScoutingDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.WheelDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.MatchScoutingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teamDaoConfig;
    private final DaoConfig competitionDaoConfig;
    private final DaoConfig competitionTeamDaoConfig;
    private final DaoConfig matchDaoConfig;
    private final DaoConfig teamScoutingDaoConfig;
    private final DaoConfig wheelDaoConfig;
    private final DaoConfig matchScoutingDaoConfig;

    private final TeamDao teamDao;
    private final CompetitionDao competitionDao;
    private final CompetitionTeamDao competitionTeamDao;
    private final MatchDao matchDao;
    private final TeamScoutingDao teamScoutingDao;
    private final WheelDao wheelDao;
    private final MatchScoutingDao matchScoutingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teamDaoConfig = daoConfigMap.get(TeamDao.class).clone();
        teamDaoConfig.initIdentityScope(type);

        competitionDaoConfig = daoConfigMap.get(CompetitionDao.class).clone();
        competitionDaoConfig.initIdentityScope(type);

        competitionTeamDaoConfig = daoConfigMap.get(CompetitionTeamDao.class).clone();
        competitionTeamDaoConfig.initIdentityScope(type);

        matchDaoConfig = daoConfigMap.get(MatchDao.class).clone();
        matchDaoConfig.initIdentityScope(type);

        teamScoutingDaoConfig = daoConfigMap.get(TeamScoutingDao.class).clone();
        teamScoutingDaoConfig.initIdentityScope(type);

        wheelDaoConfig = daoConfigMap.get(WheelDao.class).clone();
        wheelDaoConfig.initIdentityScope(type);

        matchScoutingDaoConfig = daoConfigMap.get(MatchScoutingDao.class).clone();
        matchScoutingDaoConfig.initIdentityScope(type);

        teamDao = new TeamDao(teamDaoConfig, this);
        competitionDao = new CompetitionDao(competitionDaoConfig, this);
        competitionTeamDao = new CompetitionTeamDao(competitionTeamDaoConfig, this);
        matchDao = new MatchDao(matchDaoConfig, this);
        teamScoutingDao = new TeamScoutingDao(teamScoutingDaoConfig, this);
        wheelDao = new WheelDao(wheelDaoConfig, this);
        matchScoutingDao = new MatchScoutingDao(matchScoutingDaoConfig, this);

        registerDao(Team.class, teamDao);
        registerDao(Competition.class, competitionDao);
        registerDao(CompetitionTeam.class, competitionTeamDao);
        registerDao(Match.class, matchDao);
        registerDao(TeamScouting.class, teamScoutingDao);
        registerDao(Wheel.class, wheelDao);
        registerDao(MatchScouting.class, matchScoutingDao);
    }
    
    public void clear() {
        teamDaoConfig.getIdentityScope().clear();
        competitionDaoConfig.getIdentityScope().clear();
        competitionTeamDaoConfig.getIdentityScope().clear();
        matchDaoConfig.getIdentityScope().clear();
        teamScoutingDaoConfig.getIdentityScope().clear();
        wheelDaoConfig.getIdentityScope().clear();
        matchScoutingDaoConfig.getIdentityScope().clear();
    }

    public TeamDao getTeamDao() {
        return teamDao;
    }

    public CompetitionDao getCompetitionDao() {
        return competitionDao;
    }

    public CompetitionTeamDao getCompetitionTeamDao() {
        return competitionTeamDao;
    }

    public MatchDao getMatchDao() {
        return matchDao;
    }

    public TeamScoutingDao getTeamScoutingDao() {
        return teamScoutingDao;
    }

    public WheelDao getWheelDao() {
        return wheelDao;
    }

    public MatchScoutingDao getMatchScoutingDao() {
        return matchScoutingDao;
    }

}
