package com.mechinn.android.ouralliance.greenDao.frc2014.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.mechinn.android.ouralliance.greenDao.frc2014.Competition;

import com.mechinn.android.ouralliance.greenDao.frc2014.Match;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MATCH.
*/
public class MatchDao extends AbstractDao<Match, Long> {

    public static final String TABLENAME = "MATCH";

    /**
     * Properties of entity Match.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Modified = new Property(1, java.util.Date.class, "modified", false, "MODIFIED");
        public final static Property MatchType = new Property(2, Integer.class, "matchType", false, "MATCH_TYPE");
        public final static Property MatchSet = new Property(3, Integer.class, "matchSet", false, "MATCH_SET");
        public final static Property RedScore = new Property(4, Integer.class, "redScore", false, "RED_SCORE");
        public final static Property BlueScore = new Property(5, Integer.class, "blueScore", false, "BLUE_SCORE");
        public final static Property CompLevel = new Property(6, String.class, "compLevel", false, "COMP_LEVEL");
        public final static Property MatchNum = new Property(7, String.class, "matchNum", false, "MATCH_NUM");
        public final static Property Competition = new Property(8, Long.class, "competition", false, "COMPETITION");
    };

    private DaoSession daoSession;

    private Query<Match> competition_MatchesQuery;

    public MatchDao(DaoConfig config) {
        super(config);
    }
    
    public MatchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MATCH' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MODIFIED' INTEGER," + // 1: modified
                "'MATCH_TYPE' INTEGER," + // 2: matchType
                "'MATCH_SET' INTEGER," + // 3: matchSet
                "'RED_SCORE' INTEGER," + // 4: redScore
                "'BLUE_SCORE' INTEGER," + // 5: blueScore
                "'COMP_LEVEL' TEXT," + // 6: compLevel
                "'MATCH_NUM' TEXT," + // 7: matchNum
                "'COMPETITION' INTEGER);"); // 8: competition
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MATCH'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Match entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date modified = entity.getModified();
        if (modified != null) {
            stmt.bindLong(2, modified.getTime());
        }
 
        Integer matchType = entity.getMatchType();
        if (matchType != null) {
            stmt.bindLong(3, matchType);
        }
 
        Integer matchSet = entity.getMatchSet();
        if (matchSet != null) {
            stmt.bindLong(4, matchSet);
        }
 
        Integer redScore = entity.getRedScore();
        if (redScore != null) {
            stmt.bindLong(5, redScore);
        }
 
        Integer blueScore = entity.getBlueScore();
        if (blueScore != null) {
            stmt.bindLong(6, blueScore);
        }
 
        String compLevel = entity.getCompLevel();
        if (compLevel != null) {
            stmt.bindString(7, compLevel);
        }
 
        String matchNum = entity.getMatchNum();
        if (matchNum != null) {
            stmt.bindString(8, matchNum);
        }
 
        Long competition = entity.getCompetition();
        if (competition != null) {
            stmt.bindLong(9, competition);
        }
    }

    @Override
    protected void attachEntity(Match entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Match readEntity(Cursor cursor, int offset) {
        Match entity = new Match( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // modified
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // matchType
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // matchSet
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // redScore
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // blueScore
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // compLevel
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // matchNum
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // competition
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Match entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setModified(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setMatchType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setMatchSet(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setRedScore(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setBlueScore(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setCompLevel(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMatchNum(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCompetition(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Match entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Match entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "matches" to-many relationship of Competition. */
    public List<Match> _queryCompetition_Matches(Long competition) {
        synchronized (this) {
            if (competition_MatchesQuery == null) {
                QueryBuilder<Match> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Competition.eq(null));
                queryBuilder.orderRaw("MATCH_NUM ASC");
                competition_MatchesQuery = queryBuilder.build();
            }
        }
        Query<Match> query = competition_MatchesQuery.forCurrentThread();
        query.setParameter(0, competition);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCompetitionDao().getAllColumns());
            builder.append(" FROM MATCH T");
            builder.append(" LEFT JOIN COMPETITION T0 ON T.'COMPETITION'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Match loadCurrentDeep(Cursor cursor, boolean lock) {
        Match entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Competition competition = loadCurrentOther(daoSession.getCompetitionDao(), cursor, offset);
        entity.setCompetition(competition);

        return entity;    
    }

    public Match loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Match> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Match> list = new ArrayList<Match>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Match> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Match> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
