package com.mechinn.android.ouralliance.greenDao.frc2014;

import java.util.List;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.mechinn.android.ouralliance.greenDao.frc2014.dao.MatchScoutingDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.TeamDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.TeamScoutingDao;
import com.mechinn.android.ouralliance.greenDao.frc2014.dao.WheelDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TEAM_SCOUTING.
 */
public class TeamScouting extends com.mechinn.android.ouralliance.OurAllianceObject  {

    private Long id;
    /** Not-null value. */
    private java.util.Date modified;
    private long team;
    private String notes;
    private String orientation;
    private String driveTrain;
    private Double width;
    private Double length;
    private Double heightShooter;
    private Double heightMax;
    private Integer shooterType;
    private Boolean lowGoal;
    private Boolean highGoal;
    private Double shootingDistance;
    private Boolean passGround;
    private Boolean passAir;
    private Boolean passTruss;
    private Boolean pickupGround;
    private Boolean pickupCatch;
    private Boolean pusher;
    private Boolean blocker;
    private Double humanPlayer;
    private Boolean noAuto;
    private Boolean driveAuto;
    private Boolean lowAuto;
    private Boolean highAuto;
    private Boolean hotAuto;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TeamScoutingDao myDao;

    private Team team;
    private Long team__resolvedKey;

    private List<Wheel> wheels;
    private List<MatchScouting> matches;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TeamScouting() {
    }

    public TeamScouting(Long id) {
        this.id = id;
    }

    public TeamScouting(Long id, java.util.Date modified, long team, String notes, String orientation, String driveTrain, Double width, Double length, Double heightShooter, Double heightMax, Integer shooterType, Boolean lowGoal, Boolean highGoal, Double shootingDistance, Boolean passGround, Boolean passAir, Boolean passTruss, Boolean pickupGround, Boolean pickupCatch, Boolean pusher, Boolean blocker, Double humanPlayer, Boolean noAuto, Boolean driveAuto, Boolean lowAuto, Boolean highAuto, Boolean hotAuto) {
        this.id = id;
        this.modified = modified;
        this.team = team;
        this.notes = notes;
        this.orientation = orientation;
        this.driveTrain = driveTrain;
        this.width = width;
        this.length = length;
        this.heightShooter = heightShooter;
        this.heightMax = heightMax;
        this.shooterType = shooterType;
        this.lowGoal = lowGoal;
        this.highGoal = highGoal;
        this.shootingDistance = shootingDistance;
        this.passGround = passGround;
        this.passAir = passAir;
        this.passTruss = passTruss;
        this.pickupGround = pickupGround;
        this.pickupCatch = pickupCatch;
        this.pusher = pusher;
        this.blocker = blocker;
        this.humanPlayer = humanPlayer;
        this.noAuto = noAuto;
        this.driveAuto = driveAuto;
        this.lowAuto = lowAuto;
        this.highAuto = highAuto;
        this.hotAuto = hotAuto;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTeamScoutingDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getModified() {
        return modified;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModified(java.util.Date modified) {
        this.modified = modified;
    }

    public long getTeam() {
        return team;
    }

    public void setTeam(long team) {
        this.team = team;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getOrientation() {
        return orientation;
    }

    public void setOrientation(String orientation) {
        this.orientation = orientation;
    }

    public String getDriveTrain() {
        return driveTrain;
    }

    public void setDriveTrain(String driveTrain) {
        this.driveTrain = driveTrain;
    }

    public Double getWidth() {
        return width;
    }

    public void setWidth(Double width) {
        this.width = width;
    }

    public Double getLength() {
        return length;
    }

    public void setLength(Double length) {
        this.length = length;
    }

    public Double getHeightShooter() {
        return heightShooter;
    }

    public void setHeightShooter(Double heightShooter) {
        this.heightShooter = heightShooter;
    }

    public Double getHeightMax() {
        return heightMax;
    }

    public void setHeightMax(Double heightMax) {
        this.heightMax = heightMax;
    }

    public Integer getShooterType() {
        return shooterType;
    }

    public void setShooterType(Integer shooterType) {
        this.shooterType = shooterType;
    }

    public Boolean getLowGoal() {
        return lowGoal;
    }

    public void setLowGoal(Boolean lowGoal) {
        this.lowGoal = lowGoal;
    }

    public Boolean getHighGoal() {
        return highGoal;
    }

    public void setHighGoal(Boolean highGoal) {
        this.highGoal = highGoal;
    }

    public Double getShootingDistance() {
        return shootingDistance;
    }

    public void setShootingDistance(Double shootingDistance) {
        this.shootingDistance = shootingDistance;
    }

    public Boolean getPassGround() {
        return passGround;
    }

    public void setPassGround(Boolean passGround) {
        this.passGround = passGround;
    }

    public Boolean getPassAir() {
        return passAir;
    }

    public void setPassAir(Boolean passAir) {
        this.passAir = passAir;
    }

    public Boolean getPassTruss() {
        return passTruss;
    }

    public void setPassTruss(Boolean passTruss) {
        this.passTruss = passTruss;
    }

    public Boolean getPickupGround() {
        return pickupGround;
    }

    public void setPickupGround(Boolean pickupGround) {
        this.pickupGround = pickupGround;
    }

    public Boolean getPickupCatch() {
        return pickupCatch;
    }

    public void setPickupCatch(Boolean pickupCatch) {
        this.pickupCatch = pickupCatch;
    }

    public Boolean getPusher() {
        return pusher;
    }

    public void setPusher(Boolean pusher) {
        this.pusher = pusher;
    }

    public Boolean getBlocker() {
        return blocker;
    }

    public void setBlocker(Boolean blocker) {
        this.blocker = blocker;
    }

    public Double getHumanPlayer() {
        return humanPlayer;
    }

    public void setHumanPlayer(Double humanPlayer) {
        this.humanPlayer = humanPlayer;
    }

    public Boolean getNoAuto() {
        return noAuto;
    }

    public void setNoAuto(Boolean noAuto) {
        this.noAuto = noAuto;
    }

    public Boolean getDriveAuto() {
        return driveAuto;
    }

    public void setDriveAuto(Boolean driveAuto) {
        this.driveAuto = driveAuto;
    }

    public Boolean getLowAuto() {
        return lowAuto;
    }

    public void setLowAuto(Boolean lowAuto) {
        this.lowAuto = lowAuto;
    }

    public Boolean getHighAuto() {
        return highAuto;
    }

    public void setHighAuto(Boolean highAuto) {
        this.highAuto = highAuto;
    }

    public Boolean getHotAuto() {
        return hotAuto;
    }

    public void setHotAuto(Boolean hotAuto) {
        this.hotAuto = hotAuto;
    }

    /** To-one relationship, resolved on first access. */
    public Team getTeam() {
        long __key = this.team;
        if (team__resolvedKey == null || !team__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TeamDao targetDao = daoSession.getTeamDao();
            Team teamNew = targetDao.load(__key);
            synchronized (this) {
                team = teamNew;
            	team__resolvedKey = __key;
            }
        }
        return team;
    }

    public void setTeam(Team team) {
        if (team == null) {
            throw new DaoException("To-one property 'team' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.team = team;
            team = team.getId();
            team__resolvedKey = team;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Wheel> getWheels() {
        if (wheels == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            WheelDao targetDao = daoSession.getWheelDao();
            List<Wheel> wheelsNew = targetDao._queryTeamScouting_Wheels(id);
            synchronized (this) {
                if(wheels == null) {
                    wheels = wheelsNew;
                }
            }
        }
        return wheels;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetWheels() {
        wheels = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<MatchScouting> getMatches() {
        if (matches == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MatchScoutingDao targetDao = daoSession.getMatchScoutingDao();
            List<MatchScouting> matchesNew = targetDao._queryTeamScouting_Matches(id);
            synchronized (this) {
                if(matches == null) {
                    matches = matchesNew;
                }
            }
        }
        return matches;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetMatches() {
        matches = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
