package com.mechinn.android.ouralliance.greenDao;

import com.mechinn.android.ouralliance.greenDao.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.mechinn.android.ouralliance.greenDao.dao.Event2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.EventTeam2014Dao;
import com.mechinn.android.ouralliance.greenDao.dao.TeamDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table EVENT_TEAM2014.
 */
public class EventTeam2014 extends com.mechinn.android.ouralliance.OurAllianceObject  implements Comparable<EventTeam2014> {

    private Long id;
    /** Not-null value. */
    private java.util.Date modified;
    private long EventId;
    private long teamId;
    private Integer rank;
    private Boolean scouted;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EventTeam2014Dao myDao;

    private Event2014 event2014;
    private Long event2014__resolvedKey;

    private Team team;
    private Long team__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EventTeam2014() {
    }

    public EventTeam2014(Long id) {
        this.id = id;
    }

    public EventTeam2014(Long id, java.util.Date modified, long EventId, long teamId, Integer rank, Boolean scouted) {
        this.id = id;
        this.modified = modified;
        this.EventId = EventId;
        this.teamId = teamId;
        this.rank = rank;
        this.scouted = scouted;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEventTeam2014Dao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getModified() {
        return modified;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModified(java.util.Date modified) {
        this.modified = modified;
    }

    public long getEventId() {
        return EventId;
    }

    public void setEventId(long EventId) {
        this.EventId = EventId;
    }

    public long getTeamId() {
        return teamId;
    }

    public void setTeamId(long teamId) {
        this.teamId = teamId;
    }

    public Integer getRank() {
        return rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Boolean getScouted() {
        return scouted;
    }

    public void setScouted(Boolean scouted) {
        this.scouted = scouted;
    }

    /** To-one relationship, resolved on first access. */
    public Event2014 getEvent2014() {
        long __key = this.EventId;
        if (event2014__resolvedKey == null || !event2014__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            Event2014Dao targetDao = daoSession.getEvent2014Dao();
            Event2014 event2014New = targetDao.load(__key);
            synchronized (this) {
                event2014 = event2014New;
            	event2014__resolvedKey = __key;
            }
        }
        return event2014;
    }

    public void setEvent2014(Event2014 event2014) {
        if (event2014 == null) {
            throw new DaoException("To-one property 'EventId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.event2014 = event2014;
            EventId = event2014.getId();
            event2014__resolvedKey = EventId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Team getTeam() {
        long __key = this.teamId;
        if (team__resolvedKey == null || !team__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TeamDao targetDao = daoSession.getTeamDao();
            Team teamNew = targetDao.load(__key);
            synchronized (this) {
                team = teamNew;
            	team__resolvedKey = __key;
            }
        }
        return team;
    }

    public void setTeam(Team team) {
        if (team == null) {
            throw new DaoException("To-one property 'teamId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.team = team;
            teamId = team.getId();
            team__resolvedKey = teamId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return this.getEvent2014()+" # "+this.rank+" "+this.team;
    }
    public boolean equals(Object data) {
        if(!(data instanceof EventTeam2014)) {
            return false;
        }
        return  getEvent2014().equals(((EventTeam2014)data).getEvent2014()) &&
                getTeam().equals(((EventTeam2014)data).getTeam()) &&
                getRank() == ((EventTeam2014)data).getRank() &&
                getScouted() == ((EventTeam2014)data).getScouted();
    }
    public int compareTo(EventTeam2014 another) {
        int compare = this.getRank() - another.getRank();
        if(0==compare) {
            compare = this.getTeam().compareTo(another.getTeam());
        }
        return compare;
    }
    // KEEP METHODS END

}
